### PR TITLE
Fix/fix add command parsers

### LINKED ISSUE #165: [Add] same name but with different case not marked as duplicate

### LINKED ISSUE #166: [Add supplier] same name but with extra spaces not marked as duplicate

### LINKED ISSUE #168: [Add supplier] if name input is too long, supplier tag cannot be seen

### LINKED ISSUE #187: [Add Customer] Customer specifier is case-insensitive
Executing "add Customer ..." throws invalid command format due to capitalisation of 'C'.

### PR DESCRIPTION
**Pull request by yapitsgabriel**
Fixes #165, fixes #166, fixes #168, fixes #187

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -10,14 +10,18 @@
...
+            "Names should only contain alphanumeric characters and spaces, should not be blank, and should be "
+                    + "no longer than 37 characters. ";
 
     /*
      * The first character of the address must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid input.
      */
     public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} ]*";
 
+    private static final int MAX_LENGTH = 37;
```
Comment (donkoo24) [inline src/main/java/seedu/address/model/person/Name.java]: I've already made changes such that the "staff" label wouldn't get squashed, but would cause the name to continue with "..." instead for any spillover. That should fix the issue of label getting squashed. 

But I do think there is value to capping the max length, though there should be a good reason for this that needs to be explained somewhere (DG?)
